In [2]:
import pandas as pd
import mysql.connector as sql
import numpy as np
import os
import json
import pymongo
import plotly.express as px
import openpyxl
#import matplotlib.pyplot as plt

In [3]:
file_data = open('sample_airbnb.json', "r")
jason_data = json.load(file_data)
all_data_list = []

for i in jason_data:
    dict_agg_trans = dict(id = i['_id'],
                Listing_url = i['listing_url'],
                Name = i.get('name'),
                Description = i['description'],
                House_rules = i.get('house_rules'),
                Property_type = i['property_type'],
                Room_type = i['room_type'],
                Bed_type = i['bed_type'],
                Min_nights = int(i['minimum_nights']),
                Max_nights = int(i['maximum_nights']),
                Cancellation_policy = i['cancellation_policy'],
                Accomodates = i['accommodates'],
                Total_bedrooms = i.get('bedrooms'),
                Total_beds = i.get('beds'),
                Availability_365 = i['availability']['availability_365'],
                Price = i['price'],
                Security_deposit = i.get('security_deposit'),
                Cleaning_fee = i.get('cleaning_fee'),
                Extra_people = i['extra_people'],
                Guests_included= i['guests_included'],
                No_of_reviews = i['number_of_reviews'],
                Review_scores = i['review_scores'].get('review_scores_rating'),
                Amenities = ', '.join(i['amenities']),
                Host_id = i['host']['host_id'],
                Host_name = i['host']['host_name'],
                Street = i['address']['street'],
                Country = i['address']['country'],
                Country_code = i['address']['country_code'],
                Location_type = i['address']['location']['type'],
                Longitude = i['address']['location']['coordinates'][0],
                Latitude = i['address']['location']['coordinates'][1],
                Is_location_exact = i['address']['location']['is_location_exact']
    )
    all_data_list.append(dict_agg_trans)

df = pd.DataFrame.from_dict(all_data_list)
pd.options.display.max_columns = None

In [4]:
df.head(5)

,id,Listing_url,Name,Description,House_rules,Property_type,Room_type,Bed_type,Min_nights,Max_nights,Cancellation_policy,Accomodates,Total_bedrooms,Total_beds,Availability_365,Price,Security_deposit,Cleaning_fee,Extra_people,Guests_included,No_of_reviews,Review_scores,Amenities,Host_id,Host_name,Street,Country,Country_code,Location_type,Longitude,Latitude,Is_location_exact
0,1003530,https://www.airbnb.com/rooms/1003530,New York City - Upper West Side Apt,"Murphy bed, optional second bedroom available....",No smoking is permitted in the apartment. All ...,Apartment,Private room,Real Bed,12,360,strict_14_with_grace_period,2,1.0,1.0,93,135.0,0.0,135.0,0.0,1.0,70,94.0,"Internet, Wifi, Air conditioning, Kitchen, Ele...",454250,Greta,"New York, NY, United States",United States,US,Point,-73.96523,40.79962,False
1,10133554,https://www.airbnb.com/rooms/10133554,Double and triple rooms Blue mosque,We are on the central city Blue mosque 5 minu...,,Bed and breakfast,Private room,Real Bed,1,1125,moderate,3,1.0,2.0,365,121.0,NaN,NaN,0.0,1.0,29,92.0,"Internet, Wifi, Air conditioning, Free parking...",52004703,Mehmet Emin,"Fatih , İstanbul, Turkey",Turkey,TR,Point,28.98009,41.00620,False
2,10059872,https://www.airbnb.com/rooms/10059872,"Soho Cozy, Spacious and Convenient","Clean, fully furnish, Spacious 1 bedroom flat ...",,Apartment,Entire home/apt,Real Bed,4,20,flexible,3,1.0,2.0,0,699.0,NaN,NaN,0.0,1.0,3,100.0,"Air conditioning, Kitchen, Smoking allowed, Do...",51624384,Giovanni,"Hong Kong, Hong Kong Island, Hong Kong",Hong Kong,HK,Point,114.15027,22.28158,True
3,10084023,https://www.airbnb.com/rooms/10084023,City center private room with bed,House is located 5mins walk from Sham Shui Po ...,"1. 禁止吸煙, 只限女生入住 (除得到批准) No smoking and only fe...",Guesthouse,Private room,Futon,1,500,strict_14_with_grace_period,1,1.0,1.0,220,181.0,0.0,50.0,100.0,1.0,81,92.0,"TV, Wifi, Air conditioning, Kitchen, Elevator,...",51744313,Yi,"Hong Kong , 九龍, Hong Kong",Hong Kong,HK,Point,114.16690,22.33140,True
4,10091713,https://www.airbnb.com/rooms/10091713,Surry Hills Studio - Your Perfect Base in Sydney,"This spacious, light filled studio has everyth...","No smoking: No smoking any substance, includi...",Apartment,Entire home/apt,Real Bed,10,21,strict_14_with_grace_period,2,0.0,1.0,0,181.0,300.0,50.0,0.0,1.0,64,95.0,"TV, Wifi, Kitchen, Elevator, Heating, Washer, ...",13764143,Ben,"Surry Hills, NSW, Australia",Australia,AU,Point,151.21554,-33.88029,True

In [5]:
df.shape

(5555, 32)

In [6]:
# checking Data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5555 entries, 0 to 5554
Data columns (total 32 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   5555 non-null   object
 1   Listing_url          5555 non-null   object
 2   Name                 5555 non-null   object
 3   Description          5555 non-null   object
 4   House_rules          5555 non-null   object
 5   Property_type        5555 non-null   object
 6   Room_type            5555 non-null   object
 7   Bed_type             5555 non-null   object
 8   Min_nights           5555 non-null   int64
 9   Max_nights           5555 non-null   int64
 10  Cancellation_policy  5555 non-null   object
 11  Accomodates          5555 non-null   int64
 12  Total_bedrooms       5550 non-null   float64
 13  Total_beds           5542 non-null   float64
 14  Availability_365     5555 non-null   int64
 15  Price                5555 non-null   float64
 16  Security_deposit     3471 non-null   float64
 17  Cleaning_fee         4024 non-null   float64
 18  Extra_people         5555 non-null   float64
 19  Guests_included      5555 non-null   float64
 20  No_of_reviews        5555 non-null   int64
 21  Review_scores        4081 non-null   float64
 22  Amenities            5555 non-null   object
 23  Host_id              5555 non-null   object
 24  Host_name            5555 non-null   object
 25  Street               5555 non-null   object
 26  Country              5555 non-null   object
 27  Country_code         5555 non-null   object
 28  Location_type        5555 non-null   object
 29  Longitude            5555 non-null   float64
 30  Latitude             5555 non-null   float64
 31  Is_location_exact    5555 non-null   bool
dtypes: bool(1), float64(10), int64(5), object(16)
memory usage: 1.3+ MB

In [7]:
def data_cleaning(data):
    total_row = data.shape[0]
    total_col = data.shape[1]
    null_col = (data.isnull().sum(axis=0))
    null_row = (data.isnull().sum(axis=1))
    null_col = pd.Series(null_col)
    null_row = pd.Series(null_row)
    high_missing_cols = null_col[null_col >= 1]
    high_missing_row = null_row[null_row >= 1]
    if len(high_missing_cols) > 0:
        return "ATTENTION, There are missing values in following column(s): " + ", ".join(high_missing_cols.index)
        return data
    elif len(high_missing_row) > 0:
        return "ATTENTION, There are missing values in following row(s): " + ", ".join(high_missing_row.index)
        return data
    else:
        return "No Missing Values Found",data

In [8]:
data_cleaning(df)

'ATTENTION, There are missing values in following column(s): Total_bedrooms, Total_beds, Security_deposit, Cleaning_fee, Review_scores'

In [9]:
# changing it to relevant data types
df.Price = df.Price.astype(str).astype(float)
df.Security_deposit = df.Security_deposit[~df.Security_deposit.isna()].astype(str).astype(float)
df.Cleaning_fee = df.Cleaning_fee[~df.Cleaning_fee.isna()].astype(str).astype(float)
df.Extra_people = df.Extra_people.astype(str).astype(float)
df.Guests_included = df.Guests_included.astype(str).astype(float)
df.Review_scores = df.Review_scores.astype('Int64')

In [10]:
df.isna().sum()

id                        0
Listing_url               0
Name                      0
Description               0
House_rules               0
Property_type             0
Room_type                 0
Bed_type                  0
Min_nights                0
Max_nights                0
Cancellation_policy       0
Accomodates               0
Total_bedrooms            5
Total_beds               13
Availability_365          0
Price                     0
Security_deposit       2084
Cleaning_fee           1531
Extra_people              0
Guests_included           0
No_of_reviews             0
Review_scores          1474
Amenities                 0
Host_id                   0
Host_name                 0
Street                    0
Country                   0
Country_code              0
Location_type             0
Longitude                 0
Latitude                  0
Is_location_exact         0
dtype: int64

In [ ]:
#null vaue treatment
df.dropna(subset=['Total_bedrooms'], inplace=True)
df.dropna(subset=['Total_beds'], inplace=True)
df['Security_deposit'].fillna(0, inplace=True)
df['Cleaning_fee'] = df['Cleaning_fee'].fillna(0)
df['Review_scores'] = df['Review_scores'].fillna(0)
df.Description.replace(to_replace='',value='No Description Provided',inplace=True)
df.House_rules.replace(to_replace='',value='No House rules Provided',inplace=True)
df.Amenities.replace(to_replace='',value='Not Available',inplace=True)

In [12]:
df.isna().sum()

id                     0
Listing_url            0
Name                   0
Description            0
House_rules            0
Property_type          0
Room_type              0
Bed_type               0
Min_nights             0
Max_nights             0
Cancellation_policy    0
Accomodates            0
Total_bedrooms         0
Total_beds             0
Availability_365       0
Price                  0
Security_deposit       0
Cleaning_fee           0
Extra_people           0
Guests_included        0
No_of_reviews          0
Review_scores          0
Amenities              0
Host_id                0
Host_name              0
Street                 0
Country                0
Country_code           0
Location_type          0
Longitude              0
Latitude               0
Is_location_exact      0
dtype: int64

In [13]:
df[df.duplicated()]

Empty DataFrame
Columns: [id, Listing_url, Name, Description, House_rules, Property_type, Room_type, Bed_type, Min_nights, Max_nights, Cancellation_policy, Accomodates, Total_bedrooms, Total_beds, Availability_365, Price, Security_deposit, Cleaning_fee, Extra_people, Guests_included, No_of_reviews, Review_scores, Amenities, Host_id, Host_name, Street, Country, Country_code, Location_type, Longitude, Latitude, Is_location_exact]
Index: []

In [17]:
data_cleaning(df)

('No Missing Values Found',
             id                            Listing_url  \
 0      1003530   https://www.airbnb.com/rooms/1003530
 1     10133554  https://www.airbnb.com/rooms/10133554
 2     10059872  https://www.airbnb.com/rooms/10059872
 3     10084023  https://www.airbnb.com/rooms/10084023
 4     10091713  https://www.airbnb.com/rooms/10091713
 ...        ...                                    ...
 5550   9985696   https://www.airbnb.com/rooms/9985696
 5551   9993190   https://www.airbnb.com/rooms/9993190
 5552   9887054   https://www.airbnb.com/rooms/9887054
 5553   9907907   https://www.airbnb.com/rooms/9907907
 5554   9936016   https://www.airbnb.com/rooms/9936016

                                                    Name  \
 0                   New York City - Upper West Side Apt
 1                   Double and triple rooms Blue mosque
 2                    Soho Cozy, Spacious and Convenient
 3                     City center private room with bed
 4      Surry Hills Studio - Your Perfect Base in Sydney
 ...                                                 ...
 5550                                    Kadıköy-Altıyol
 5551  Just Steps from the Ocean at Premier Platinum ...
 5552                Quarry Bay fully furnished studio C
 5553                         Large double room in Bondi
 5554                        Alugo Apartamento na Tijuca

                                             Description  \
 0     Murphy bed, optional second bedroom available....
 1     We are on the central city  Blue mosque 5 minu...
 2     Clean, fully furnish, Spacious 1 bedroom flat ...
 3     House is located 5mins walk from Sham Shui Po ...
 4     This spacious, light filled studio has everyth...
 ...                                                 ...
 5550  Kadıköy merkezde 2+1 dairem vardır.Çok kalabal...
 5551  Relax Hawaiian Style in Gated Community on Oce...
 5552   Newly renovated studio flat with full furniture.
 5553  A bright large double room is available in a b...
 5554  Apartamento amplo que acomoda 6 pessoas. Um qu...

                                             House_rules      Property_type  \
 0     No smoking is permitted in the apartment. All ...          Apartment
 1                               No House rules Provided  Bed and breakfast
 2                               No House rules Provided          Apartment
 3     1. 禁止吸煙, 只限女生入住 (除得到批准) No smoking and only fe...         Guesthouse
 4     No smoking:  No smoking any substance, includi...          Apartment
 ...                                                 ...                ...
 5550                            No House rules Provided              House
 5551  As a guest of Coconut Condos, I agree to the f...          Townhouse
 5552                            No House rules Provided          Apartment
 5553  We like to keep the flat clean and tidy so wou...          Apartment
 5554  Cuidar das instalações e objetos da casa em pe...          Apartment

             Room_type  Bed_type  Min_nights  Max_nights  \
 0        Private room  Real Bed          12         360
 1        Private room  Real Bed           1        1125
 2     Entire home/apt  Real Bed           4          20
 3        Private room     Futon           1         500
 4     Entire home/apt  Real Bed          10          21
 ...               ...       ...         ...         ...
 5550  Entire home/apt  Real Bed           1        1125
 5551  Entire home/apt  Real Bed           3         365
 5552     Private room  Real Bed           3        1125
 5553     Private room  Real Bed           3        1125
 5554  Entire home/apt  Real Bed           1        1125

               Cancellation_policy  Accomodates  Total_bedrooms  Total_beds  \
 0     strict_14_with_grace_period            2             1.0         1.0
 1                        moderate            3             1.0         2.0
 2                        flexible            3             1.0         2.0
 3     strict_14_with_grace_period            1             1.0         1.0
 4     strict_14_with_grace_period            2             0.0         1.0
 ...                           ...          ...             ...         ...
 5550                     flexible            2             2.0         3.0
 5551  strict_14_with_grace_period            6             2.0         4.0
 5552                     flexible            1             1.0         1.0
 5553                     moderate            2             1.0         1.0
 5554                     flexible            6             1.0         2.0

       Availability_365  Price  Security_deposit  Cleaning_fee  Extra_people  \
 0                   93  135.0               0.0         135.0           0.0
 1                  365  121.0               0.0           0.0           0.0
 2                    0  699.0               0.0           0.0           0.0
 3                  220  181.0               0.0          50.0         100.0
 4                    0  181.0             300.0          50.0           0.0
 ...                ...    ...               ...           ...           ...
 5550               365  501.0               0.0           0.0           0.0
 5551               258  220.0             200.0         315.0           0.0
 5552               353  400.0            3000.0           0.0         300.0
 5553                 0   60.0               0.0          50.0          50.0
 5554                 0  750.0               0.0           0.0           0.0

       Guests_included  No_of_reviews  Review_scores  \
 0                 1.0             70             94
 1                 1.0             29             92
 2                 1.0              3            100
 3                 1.0             81             92
 4                 1.0             64             95
 ...               ...            ...            ...
 5550              1.0              0              0
 5551              1.0             15             92
 5552              2.0              4             85
 5553              2.0              0              0
 5554              1.0              0              0

                                               Amenities   Host_id  \
 0     Internet, Wifi, Air conditioning, Kitchen, Ele...    454250
 1     Internet, Wifi, Air conditioning, Free parking...  52004703
 2     Air conditioning, Kitchen, Smoking allowed, Do...  51624384
 3     TV, Wifi, Air conditioning, Kitchen, Elevator,...  51744313
 4     TV, Wifi, Kitchen, Elevator, Heating, Washer, ...  13764143
 ...                                                 ...       ...
 5550  TV, Cable TV, Internet, Wifi, Kitchen, Buzzer/...  51303748
 5551  TV, Wifi, Air conditioning, Pool, Kitchen, Fre...  51013381
 5552  TV, Wifi, Air conditioning, Kitchen, Elevator,...  31386255
 5553  TV, Internet, Wifi, Kitchen, Washer, Dryer, Sm...  47615848
 5554  TV, Cable TV, Internet, Wifi, Air conditioning...  47092481

            Host_name                                  Street        Country  \
 0              Greta             New York, NY, United States  United States
 1        Mehmet Emin                Fatih , İstanbul, Turkey         Turkey
 2           Giovanni  Hong Kong, Hong Kong Island, Hong Kong      Hong Kong
 3                 Yi               Hong Kong , 九龍, Hong Kong      Hong Kong
 4                Ben             Surry Hills, NSW, Australia      Australia
 ...              ...                                     ...            ...
 5550            Eren               Kadıköy, İstanbul, Turkey         Turkey
 5551  Coconut Condos              Lahaina, HI, United States  United States
 5552             Cat  Hong Kong, Hong Kong Island, Hong Kong      Hong Kong
 5553            Lucy             Bondi Beach, NSW, Australia      Australia
 5554          Aliane  Rio de Janeiro, Rio de Janeiro, Brazil         Brazil

      Country_code Location_type   Longitude   Latitude  Is_location_exact  \
 0              US         Point  -73.965230  40.799620              False
 1              TR         Point   28.980090  41.006200              False
 2              HK         Point  114.150270  22.281580               True
 3              HK         Point  114.166900  22.331400               True
 4              AU         Point  151.215540 -33.880290               True
 ...           ...           ...         ...        ...                ...
 5550           TR         Point   29.030790  40.985630              False
 5551           US         Point -156.667520  20.858940              False
 5552           HK         Point  114.207220  22.291570              False
 5553           AU         Point  151.265420 -33.892980              False
 5554           BR         Point  -43.173761 -22.908336              False

           continent
 0               usa
 1              asia
 2              asia
 3              asia
 4             world
 ...             ...
 5550           asia
 5551            usa
 5552           asia
 5553          world
 5554  south america

 [5539 rows x 33 columns])

In [16]:
df.to_csv('data.csv',index=False)